name = "nhentai"
type = 'webpack'
account_id = ''
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
